export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const SET_USER = "SET_USER";

export const LOAD_CATEGORIES = "LOAD_CATEGORIES";
export const ADD_CATEGORIES = "ADD_CATEGORIES";
export const SELECT_CATEGORIES = "SELECT_CATEGORIES";
export const REMOVE_CATEGORIES = "REMOVE_CATEGORIES";
export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const DELETE_CATEGORIES = "DELETE_CATEGORIES";

export const LOAD_MATERIALS = "LOAD_MATERIALS";
export const ADD_MATERIALS = "ADD_MATERIALS";
export const SELECT_MATERIALS = "SELECT_MATERIALS";
export const REMOVE_MATERIALS = "REMOVE_MATERIALS";
export const UPDATE_MATERIALS = "UPDATE_MATERIALS";
export const DELETE_MATERIALS = "DELETE_MATERIALS";

export const LOAD_COLORS = "LOAD_COLORS";
export const ADD_COLORS = "ADD_COLORS";
export const SELECT_COLORS = "SELECT_COLORS";
export const REMOVE_COLORS = "REMOVE_COLORS";
export const UPDATE_COLORS = "UPDATE_COLORS";
export const DELETE_COLORS = "DELETE_COLORS";

export const LOAD_SIZES = "LOAD_SIZES";
export const ADD_SIZES = "ADD_SIZES";
export const SELECT_SIZES = "SELECT_SIZES";
export const REMOVE_SIZES = "REMOVE_SIZES";
export const UPDATE_SIZES = "UPDATE_SIZES";
export const DELETE_SIZES = "DELETE_SIZES";

export const LOAD_SUPPLIERS = "LOAD_SUPPLIERS";
export const ADD_SUPPLIERS = "ADD_SUPPLIERS";
export const SELECT_SUPPLIERS = "SELECT_SUPPLIERS";
export const REMOVE_SUPPLIERS = "REMOVE_SUPPLIERS";
export const UPDATE_SUPPLIERS = "UPDATE_SUPPLIERS";
export const DELETE_SUPPLIERS = "DELETE_SUPPLIERS";

export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const SELECT_PRODUCTS = "SELECT_PRODUCTS";
export const REMOVE_PRODUCTS = "REMOVE_PRODUCTS";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const DELETE_PRODUCTS = "DELETE_PRODUCTS";

export const LOAD_PRODUCTSAVAILABLE = "LOAD_PRODUCTSAVAILABLE";
export const ADD_PRODUCTSAVAILABLE = "ADD_PRODUCTSAVAILABLE";
export const SELECT_PRODUCTSAVAILABLE = "SELECT_PRODUCTSAVAILABLE";
export const REMOVE_PRODUCTSAVAILABLE = "REMOVE_PRODUCTSAVAILABLE";
export const UPDATE_PRODUCTSAVAILABLE = "UPDATE_PRODUCTSAVAILABLE";
export const DELETE_PRODUCTSAVAILABLE = "DELETE_PRODUCTSAVAILABLE";

export const SET_RESERVATION = "SET_RESERVATION";
export const CLEAR_RESERVATION = "CLEAR_RESERVATION";

export const LOAD_ADMIN_RESERVATIONS = "LOAD_ADMIN_RESERVATIONS";
export const ADMIN_RESERVATION_STATUS_CHANGE =
  "ADMIN_RESERVATION_STATUS_CHANGE";
export const ADMIN_RESERVATION_DELETE = "ADMIN_RESERVATION_DELETE";

export const ADD_RESERVATION = "ADD_RESERVATION";
export const LOAD_ALL_RESERVATION = "LOAD_ALL_RESERVATION";
export const SELECT_RESERVATION = "SELECT_RESERVATION";
export const REMOVE_RESERVATION = "REMOVE_RESERVATION";
export const UPDATE_RESERVATION = "UPDATE_RESERVATION";
export const DELETE_RESERVATION = "DELETE_RESERVATION";
export const LOAD_ALL_RESERVATION_BY_USER = "LOAD_ALL_RESERVATION_BY_USER";

export const SET_CART = "SET_CART";
export const CLEAR_CART = "CLEAR_CART";
