export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const SET_USER = 'SET_USER';

export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const ADD_CATEGORIES = 'ADD_CATEGORIES';
export const SELECT_CATEGORIES = 'SELECT_CATEGORIES';
export const REMOVE_CATEGORIES = 'REMOVE_CATEGORIES';
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
export const DELETE_CATEGORIES = 'DELETE_CATEGORIES';

export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const SELECT_PRODUCTS = 'SELECT_PRODUCTS';
export const REMOVE_PRODUCTS = 'REMOVE_PRODUCTS';
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';


export const LOAD_PRODUCTSAVAILABLE = 'LOAD_PRODUCTSAVAILABLE';
export const ADD_PRODUCTSAVAILABLE = 'ADD_PRODUCTSAVAILABLE';
export const SELECT_PRODUCTSAVAILABLE = 'SELECT_PRODUCTSAVAILABLE';
export const REMOVE_PRODUCTSAVAILABLE = 'REMOVE_PRODUCTSAVAILABLE';
export const UPDATE_PRODUCTSAVAILABLE = 'UPDATE_PRODUCTSAVAILABLE';
export const DELETE_PRODUCTSAVAILABLE = 'DELETE_PRODUCTSAVAILABLE';


export const SET_RESERVATION = 'SET_RESERVATION';
export const CLEAR_RESERVATION = 'CLEAR_RESERVATION';

export const LOAD_ADMIN_RESERVATIONS = 'LOAD_ADMIN_RESERVATIONS';
export const ADMIN_RESERVATION_STATUS_CHANGE = 'ADMIN_RESERVATION_STATUS_CHANGE';
export const ADMIN_RESERVATION_DELETE = 'ADMIN_RESERVATION_DELETE';